### ISSUE TITLE
Dogecoin test address fails to get read in.

### ISSUE THREAD

**Issue by shawnpringle** [Coinomi/coinomi-android#24] opened 2015-05-21 17:20 UTC
open the test wallet.  I sent 200,000 test DOGE coins to this wallet.  I tried to send it back to my dogecoin-qt.  I generated the QR code and it seems to fill in but I get an error.  It says there was a problem scanning:
dogecoin:
dogecoin:njx9J5HeYuXmRz5eaLrho6dro92FoBiveG

The Dogecoin address appears momentarily on the screen and in 600 ms I cannot compare the address on the two clients to ensure they are really the same but after several attempts, I see that the last five letters and the first five letters are the same.

Reproduce like this:  Get some test dogecoins.  CPU mining works.  Paste the address with 'dogecoin:njx9J5HeYuXmRz5eaLrho6dro92FoBiveG' into some qr code generator.  dogecoin-qt uses the 'dogecoin:' part as well when creating the QR code.  In other words, the URI not the bare address to generate the QR code.  Try to scan the address to pay in the app from the qr code generator.  It will say it was unable to validate it.  I tried pasting only the bare dogecoin address into a qr code generator and it did read it.

1. Clients should be able to read QR-codes from distinct clients.
2. Since the Satoshi client uses the URI form, other clients should be able to understand this form as well.
3. Please make the client accept the URI form.

It is probably a good idea to also parse bare addresses because they might be in use by other clients.

**Comment by erasmospunk** [comment] 2015-05-21 17:56
Thanks for reporting this bug, I could reproduce it.

It seems that with the latest code that handles the URIs broke the testnet compatibility.

**Comment by erasmospunk** [comment] 2015-05-21 18:03
Also tried a QR code of a bare address and it fails scanning from the Balance screen but it works from the Send screen (there is slightly different logic there).

**Comment by shawnpringle** [comment] 2015-05-21 18:14
The URI address from the balance screen fails with illegal character ':' error.  It isn't better than the other one.  Logic for validation should be in one place for all coins.  Pass the name of the coin, and whether it is from a bitcoin derived type of address (coins whose code base start's with Satoshi's client), and then the same routine can check the URI has that prefix string, decode and validate the checksum and return with the bare address and a flag indicating whether it is valid.

**Comment by erasmospunk** [comment] 2015-05-21 18:46
So getting to the root of it, the [CoinURI](https://github.com/Coinomi/coinomi-android/blob/master/core/src/main/java/com/coinomi/core/uri/CoinURI.java#L147) and the [CoinID](https://github.com/Coinomi/coinomi-android/blob/master/core/src/main/java/com/coinomi/core/coins/CoinID.java#L100) make the incorrect assumption that the a specific URI can have a single CoinType. For `dogecoin:` they always choose `DogecoinMain` but in our case we want the `DogecoinTest` CoinType.

The error message with the "illegal character ':'" happens because it tries to parse the scanned string as URI and fails, then it tries to parse it as a bare address and fails again because of the invalid character.

**Comment by erasmospunk** [comment] 2015-06-21 15:23
Resolved in the latest version.

**Closed by erasmospunk** 2015-06-21 15:23 UTC
Labels: bug
