### ISSUE TITLE
Battery depletion in android standby mode.

### ISSUE THREAD

**Issue by cherouvim** [Coinomi/coinomi-android#165] opened 2017-05-22 19:47 UTC
This has happened 3 times. I check my coinomi wallet for 30 seconds or something. Then I click on the hardware power button of my device in order to turn off the screen and leave the device next to me. After 90 minutes I grab the device and it's smoking hot. I activate the screen and see that battery has gone from 60% to 7%. I open the settings > apps and see that coinomi has consumed a lot of battery. Screenshot attached. The marked red circle with the sudden batter drop represents the 90 minutes that the device was on standby.

Device: plusone 3t

![screenshot_20170522-195955](https://cloud.githubusercontent.com/assets/743305/26325677/91fe82fc-3f40-11e7-97ae-bcc0e76c4574.png)

**Comment by GeorgeKimionis** [comment] 2017-06-19 21:55
Thanks for reporting this. We had no other complaints so far regarding battery usage, however we will investigate it. What was the version of Coinomi you had installed at that time?

**Comment by cherouvim** [comment] 2017-06-22 08:07
I had the currently latest version at that time.

I haven't had this incident happen again since then, so maybe it was random and dependent on my android device.

**Comment by GeorgeKimionis** [comment] 2017-06-24 01:51
We tested this in several devices and couldn't reproduce it. Closing for now.

**Closed by GeorgeKimionis** 2017-06-24 01:51 UTC

**Comment by gagdiez** [comment] 2017-10-14 17:46
Hi, I'll like to report I have exactly the same issue.
